//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.ISchoolService")]
    public interface ISchoolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetPerson", ReplyAction="http://tempuri.org/ISchoolService/GetPersonResponse")]
        DataTransfer.PersonDTO GetPerson(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetTeachers", ReplyAction="http://tempuri.org/ISchoolService/GetTeachersResponse")]
        System.Collections.Generic.List<DataTransfer.PersonDTO> GetTeachers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/IsLoginValid", ReplyAction="http://tempuri.org/ISchoolService/IsLoginValidResponse")]
        bool IsLoginValid(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/AddSupplement", ReplyAction="http://tempuri.org/ISchoolService/AddSupplementResponse")]
        bool AddSupplement(long subjectId, int day, int order, long teacherId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/AddSupplementCancel", ReplyAction="http://tempuri.org/ISchoolService/AddSupplementCancelResponse")]
        bool AddSupplementCancel(long subjectId, int day, int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/GetSupplements", ReplyAction="http://tempuri.org/ISchoolService/GetSupplementsResponse")]
        System.Collections.Generic.List<DataTransfer.SupplementDTO> GetSupplements(long subjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/TestGetGrades", ReplyAction="http://tempuri.org/ISchoolService/TestGetGradesResponse")]
        System.Collections.Generic.List<DataTransfer.GradeDTO> TestGetGrades();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolServiceChannel : Web.WebService.ISchoolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolServiceClient : System.ServiceModel.ClientBase<Web.WebService.ISchoolService>, Web.WebService.ISchoolService {
        
        public SchoolServiceClient() {
        }
        
        public SchoolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTransfer.PersonDTO GetPerson(long id) {
            return base.Channel.GetPerson(id);
        }
        
        public System.Collections.Generic.List<DataTransfer.PersonDTO> GetTeachers() {
            return base.Channel.GetTeachers();
        }
        
        public bool IsLoginValid(string username, string password) {
            return base.Channel.IsLoginValid(username, password);
        }
        
        public bool AddSupplement(long subjectId, int day, int order, long teacherId) {
            return base.Channel.AddSupplement(subjectId, day, order, teacherId);
        }
        
        public bool AddSupplementCancel(long subjectId, int day, int order) {
            return base.Channel.AddSupplementCancel(subjectId, day, order);
        }
        
        public System.Collections.Generic.List<DataTransfer.SupplementDTO> GetSupplements(long subjectId) {
            return base.Channel.GetSupplements(subjectId);
        }
        
        public System.Collections.Generic.List<DataTransfer.GradeDTO> TestGetGrades() {
            return base.Channel.TestGetGrades();
        }
    }
}
